### ISSUE TITLE
INFO : Contenu html 

### ISSUE THREAD

**Issue by EC2311** [yllen/reports#11]
Bonjour

Version mysql 5.7.24

soit la table glpi_tickettasks (par exemple)
cette table comporte un champs content qui contient une données html : ok

je cree un report
et j'aimerais visualiser cette colonne avec le design qu'elle contient

en php on peut utiliser la fonction "htmlspecialchars_decode".

comment faire pour utiliser cette fonction dans le report ? ou peut etr eune fonction mysql (mais je n'ai pas trouvé)
Merci

**Comment by yllen** [comment]
pouvez-vous me donner votre exemple de champ content avec les données html ?

**Comment by EC2311** [comment]
bonjour
Merci pour votre attention
dans la glpi_tickettasks, cette zone se nomme 'content'
elle contient le contenu de la tache que l'on peut creer dans le ticket (par exemple)

Merci

**Comment by yllen** [comment]
oui, j'ai bien compris cela, mais dans une tâche vous n'avez pas tout le principe d'ajout de texte en Html comme dans les tickets.
Donc j'ai besoin d'avoir le contenu de votre zone content pour voir la structure exacte de votre Html

**Comment by EC2311** [comment]
Bonjour Yllen,

tout ce que je sais c'est que si j'utilise "htmlspecialchars_decode" dans un script php quelconque , cette fonction repond entierement à mes besoins... (tant pour la zone content de glpi_tickets que pour la zone content de glpi_tickettasks)
mais je ne sais pas comment je pourrais intercaler cette fonction dans le report 
ou peut etre creer une fonction (comme les headings ?) qui permettrait de faire la conversion ?

**Comment by EC2311** [comment]
Bonjour
j'ai trouvé solution

dans la classe inc/column.class.php
![image](https://user-images.githubusercontent.com/42341169/182625690-3df847fc-4745-40eb-b214-3424c3dc054c.png)

le fait d'ajouter la fonction htmlspecialchars_decode permet un affichage cohérent

**Comment by yllen** [comment]
Changer pour toutes les colonnes peut introduire une régression.
Pour éviter cela, j'ai créé un nouveau type columnHtml à substituer à column (new PluginReportsColumnHtml)

**Comment by EC2311** [comment]
Bonjour

Meilleurs voeux 

dans les titres de colonnes je souhaite mettre les titres sur 2 lignes : je spécifie br avec les <> : ok ca marche

si on souhaite eviter les retours à la ligne automatique lors de blanc, je remplace le ' ' par &nbsp
autant sur le report interactif cela passe, mais lors de l'export, on voit &amp (traduction du &) et nbsp;

en spécifiant <pre>titi toto</pre> cela passe ... mais niveau interactif on perd le caractere gras de la mise en page initiale...

que pourrait-on faire pour prendre en compte le '&nbsp' ?
Merci
