### ISSUE TITLE
GLPI 10 compatibility

### ISSUE THREAD

**Issue by alejandroed** [yllen/reports#5]
Hi!

GLPI 10 stable it's just around the corner, have you plans to bring compatibility to reports plugin?

**Comment by Wolvverine** [comment]
When is the version for GLPI 10.x planned ?

**Comment by paulz1** [comment]
Same question... Does the version for GLPI 10.x is planned ?

**Comment by waaalex** [comment]
same

**Comment by GroobyKJ** [comment]
bumpp

**Comment by Mirkk** [comment]
No plans to go to v10 for this plugin? Are there recommendet alternatives for generating reports (and as API to create reports)? Are there plans to include this API in GLPI? Thank you very much! @orthagh @yllen

**Comment by cosmedd** [comment]
In case anyone is interested. The changes in this pull request:

https://github.com/yllen/reports/pull/6

seem to allow the reporting plugin to run smoothly in GLPI 10.

**Comment by Wolvverine** [comment]
Code for v10 is here:

https://github.com/InfotelGLPI/reports/tree/PrepareGLPI10
